MMS/MMS/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from . import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATICFILES_DIRS)

MMS/core/urls.py
from django.urls import path
from . import views

app_name="core"

urlpatterns = [
    path('', views.home, name="home" ),
    path('about/', views.about, name="about" ),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('student_access/', views.student_access, name='student_access'),
     path('edit-student/<int:student_id>/', views.edit_student, name='edit_student'),
    path('delete-student/<int:student_id>/', views.delete_student, name='delete_student'),
    path('edit-teacher/<int:teacher_id>/', views.edit_teacher, name='edit_teacher'),
    path('delete-teacher/<int:teacher_id>/', views.delete_teacher, name='delete_teacher'),
    path('view_grades/<int:student_id>/', views.view_student_grades, name='view_student_grades'),
    path('teachers_dashboard/', views.teacher_dashboard, name="teacher_dashboard" ),
   
    path('grades/<int:student_id>/', views.add_or_edit_grades, name='submit_grades'),
    path('delete/<int:pk>/', views.delete_admin, name="delete_me"),

    path('login/', views.custom_login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('logout_stud/', views.logout_student, name='logout_student'),
    path('teacher/edit/<int:pk>/', views.edit_teacher, name='edit_teacher'),
    path('teacher/delete/<int:pk>/', views.delete_teacher, name='delete_teacher'),
    path('register-admin/', views.register_admin, name='register_admin'),
]

MMS/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    <link rel="stylesheet" href="{% static 'css/home.css' %}">
    <link href="{% static "css/tailwind.min.css" %}" rel="stylesheet">
    
</head>
<body>
    <header>
    <h1 style="color:#fff;">WEL COME TO MARKING MANAGEMENT SYSTEM</h1>
    <p>Your Result Hub</p>
  </header>

  <nav>
    <a href="{% url 'core:home' %}">Home</a>
    <a href="{% url 'core:student_access' %}">Student</a>
    <a href="{% url 'core:teacher_dashboard' %}">Teacher</a>
    <a href="{% url 'core:login' %}">Login</a>
    {% if request.user.is_authenticated %}
      <a href="{% url 'core:logout' %}">Logout</a>
      <a href="{% url 'core:admin_dashboard' %}">Dashboard</a>
    {% endif %}
    <a href="{% url 'core:about' %}">About</a>
  </nav>
    {% block content %}
    {% endblock content %}
    <footer>
    &copy; 2025 USMAN'S MARKING MANAGEMENT SYSTEM. All rights reserved.
  </footer>
</body>
</html>